USE movies;

CALL SET_TITLES();
CALL FILL_TIME_DIM(1901, 2023);
CALL BIND_TIME_DIM();
CALL SET_DURATION();
CALL FILL_DIRECTOR_DIM();
CALL BIND_DIRECTOR_DIM();
CALL SET_SALES();
CALL SET_RATING();
CALL FILL_LICENSE_DIM();
CALL BIND_LICENSE_DIM();
CALL FILL_MEDIA_DIM();
CALL BIND_MEDIA_DIM();
CALL FILL_NSFW_DIM();
CALL BIND_NSFW_DIM();
CALL FILL_DISTRIBUTOR_DIM();
CALL BIND_DISTRIBUTOR_DIM();
CALL FILL_GENRE_DIM();
CALL BIND_GENRE_DIM();

DROP TABLE IF EXISTS stage_films;
DROP TABLE IF EXISTS stage_imdb;
DROP TABLE IF EXISTS stage_nsfw;
DROP TABLE IF EXISTS stage_sales;

SELECT * FROM dim_media_type;
SELECT * FROM dim_license;
SELECT * FROM dim_genre;
SELECT * FROM dim_distributor;
SELECT * FROM dim_nsfw;
SELECT * FROM dim_director;
SELECT * FROM fact_movie;